tarsier/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('product/', views.product, name='product'),
    path('product_detail/<int:pk>', views.product_detail, name='product_detail'),
    path('blog/', views.blog, name='blog'),
    path('blog_detail/<int:pk>', views.blog_detail, name='blog_detail'),
]

tarsier/tarsier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tarsier/main/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=150, unique=True)
    product_description = models.TextField()
    product_image = models.ImageField(upload_to='product', null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name


class Blog(models.Model):
    blog_name = models.CharField(max_length=150, unique=True)
    blog_description = models.TextField()
    blog_image = models.ImageField(upload_to='blog', null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog_name

tarsier/main/views.py
from django.shortcuts import render
from main.models import Product, Blog


def index(request):
    blogs = Blog.objects.all()
    context = {
        'blogs': blogs,
    }
    return render(request, 'main/index.html', context)


def contact(request):
    return render(request, 'main/contact.html')


def product(request):
    products = Product.objects.all()
    return render(request, 'main/product.html', context={'products': products})


def product_detail(request,pk):
    product = Product.objects.get(id=pk)
    return render(request, 'main/product-details.html', context={'product': product})


def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'main/blog.html', context={'blogs': blogs})


def blog_detail(request,pk):
    blog = Blog.objects.get(id=pk)
    return render(request, 'main/blog-details.html', context={'blog': blog})

tarsier/main/templates/main/partials/_footer.html
{% load static %}
<!-- main-footer -->
<footer class="main-footer footer-style-three">
    <div class="footer-top-two">
        <div class="pattern-layer">
            <div class="pattern-1" style="background-image: url({% static 'main/assets/images/shape/shape-21.png' %});"></div>
            <div class="pattern-2" style="background-image: url({% static 'main/assets/images/shape/shape-22.png' %});"></div>
        </div>
        <div class="auto-container" style="max-width: 1200px;">
            <div class="row clearfix">
                <div class="col-lg-4 col-md-6 col-sm-12 footer-column">
                    <div class="footer-widget logo-widget">
                        <figure class="footer-logo">
                            <a href="{% url 'main:index' %}">
                                <span class="row align-items-center gap-3" style="margin-top: 20%">
                                    <img src="{% static 'main/assets/images/brand.png' %}" alt="" style="width: 100%;max-width: 90px">
                                    <span class="brand-text" style="color: white;font-size: 45px">tars<span style="color: #ff009c">i</span>er</span>
                                </span>
                            </a>
                        </figure>
                        <!-- social icons -->
                        <ul class="social-links clearfix">
                            <li><a href="//www.linkedin.com/company/tarsier-technology/"><i class="fab fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 footer-column">
                    <div class="footer-widget links-widget ml-40">
                        <div class="widget-title">
                            <h3>Useful Links</h3>
                        </div>
                        <!-- footer links -->
                        <div class="widget-content">
                            <ul class="links-list clearfix">
                                <li><a href="{% url 'main:index' %}">Home</a></li>
                                <li><a href="{% url 'main:product' %}">Product</a></li>
                                <li><a href="{% url 'main:blog' %}">Blog</a></li>
                                <li><a href="{% url 'main:contact' %}">Contact Us</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 footer-column">
                    <div class="footer-widget contact-widget">
                        <div class="widget-title">
                            <h3>Contact Us</h3>
                        </div>
                        <div class="widget-content">
                            <ul class="info-list clearfix">
                                <li>
                                    <h4>Office Location</h4>
                                    <p>Çamlaraltı Mah. Hüseyin Yılmaz Cd.No:67 B Blok G07 Pamukkale/DENİZLİ</p>
                                </li>
                                <li>
                                    <h4>Email Address</h4>
                                    <p><a href="mailto:info@tarsierteknoloji.com">info@tarsierteknoloji.com</a></p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <!-- scroll to top -->
        <button class="scroll-top style-one scroll-to-target" data-target="html">
            <i class="fas fa-angle-up"></i>
        </button>
        <div class="auto-container">
            <div class="bottom-inner clearfix">
                <div class="copyright text-center">
                    <p style="color: #cccccc"><span style="margin-right: 10px">&copy;2023</span>Tarsier</p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- main-footer end -->

tarsier/main/templates/main/partials/_main-navbar.html
{% load static %}
<!-- main header -->
<header class="main-header header-style-three">
    <!-- header-lower -->
    <div class="header-lower">
        <div class="auto-container">
            <div class="outer-box clearfix">
                <!-- banner -->
                <div class="logo-box pull-left">
                    <figure class="logo">
                        <a href="{% url 'main:index' %}">
                            <span class="row align-items-center">
                                <img class="brand" src="{% static 'main/assets/images/brand.png' %}" alt="">
                                <span class="brand-text" style="color: white">tars<span style="color: #ff009c">i</span>er</span>
                            </span>

                        </a>
                    </figure>
                </div>
                <!-- end banner -->
                <div class="menu-area pull-right clearfix">
                    <!--Mobile Navigation Toggler-->
                    <div class="mobile-nav-toggler">
                        <i class="icon-bar"></i>
                        <i class="icon-bar"></i>
                        <i class="icon-bar"></i>
                    </div>
                    <nav class="main-menu navbar-expand-md navbar-light">
                        <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                            <ul class="navigation clearfix">
                                <li class="current">
                                    <a href="{% url 'main:index' %}">Home</a>
                                </li>
                                <li class="nav-link">
                                    <a href="{% url 'main:product' %}">Product</a>
                                </li>
                                <li class="nav-link">
                                    <a href="{% url 'main:blog' %}">Blog</a>
                                </li>
                                <li class="nav-link">
                                    <a href="{% url 'main:contact' %}">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <!--sticky Header-->
    <div class="sticky-header">
        <div class="auto-container">
            <div class="outer-box clearfix">
                <figure class="sticky-logo pull-left">
                    <a href="{% url 'main:index' %}">
                        <span class="row align-items-center gap-3">
                            <img class="brand" src="{% static 'main/assets/images/brand.png' %}" alt="">
                            <span class="brand-text">tars<span style="color: #ff009c">i</span>er</span>
                        </span>
                    </a>
                </figure>
                <div class="menu-area pull-right clearfix">
                    <nav class="main-menu clearfix">
                        <!--Keep This Empty / Menu will come through Javascript-->
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- main-header end -->

tarsier/main/templates/main/partials/_mobile-menu.html
{% load static %}
<!-- Mobile Menu  -->
<div class="mobile-menu">
    <div class="menu-backdrop"></div>
    <div class="close-btn"><i class="fas fa-times"></i></div>

    <nav class="menu-box">
        <div class="nav-logo">
            <a href="{% url 'main:index' %}">
                <span class="row align-items-center gap-3">
                    <img class="brand" src="{% static 'main/assets/images/brand.png' %}" alt="" title="">
                    <span class="brand-text" style="color: white">tars<span style="color: #ff009c">i</span>er</span>
                </span>
            </a>
        </div>
        <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
        <div class="contact-info">
            <h4>Contact Info</h4>
            <ul>
                <li>Çamlaraltı Mah. Hüseyin Yılmaz Cd.No:67 B Blok G07 Pamukkale/DENİZLİ</li>
                <li><a href="mailto:info@tarsierteknoloji.com">info@tarsierteknoloji.com</a></li>
            </ul>
        </div>
        <div class="social-links">
            <ul class="clearfix">
                <li><a href="//www.linkedin.com/company/tarsier-technology/"><span class="fab fa-linkedin"></span></a></li>
            </ul>
        </div>
    </nav>
</div>
<!-- End Mobile Menu -->

tarsier/main/templates/main/partials/_pre-loader.html
<!-- preloader -->
<div class="loader-wrap">
    <div class="preloader">
        <div class="preloader-close">x</div>
        <div id="handle-preloader" class="handle-preloader">
            <div class="animation-preloader">
                <div class="spinner"></div>
                <div class="txt-loading">
                    <span data-text-preloader="t" class="letters-loading">
                        t
                    </span>
                    <span data-text-preloader="a" class="letters-loading">
                        a
                    </span>
                    <span data-text-preloader="r" class="letters-loading">
                        r
                    </span>
                    <span data-text-preloader="s" class="letters-loading">
                        s
                    </span>
                    <span data-text-preloader="i" class="letters-loading">
                        i
                    </span>
                    <span data-text-preloader="e" class="letters-loading">
                        e
                    </span>
                    <span data-text-preloader="r" class="letters-loading">
                        r
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- preloader end -->