aiproject/web/aiproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('upload/', include('upload.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aiproject/web/media/project-files/Ai-Project-try_branch/uploadPage/uploadPage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('upload.urls')),

]

# from django.urls import path
# from upload import views
#
# urlpatterns = [
#     path('upload-zip/', views.upload_zip, name='upload_zip'),
# ]

aiproject/web/project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='project'),
    path('create-project/', views.create_project, name='create-project'),
    path('project/<int:pk>', views.project_detail, name='project-detail'),
    path('project/<int:pk>/delete/', views.delete_project, name='delete-project'),
    path('project/colorspace/<int:pk>', views.color_space, name='color-space'),
    path('project/colorspace/<str:color_space>', views.change_image, name='change_image'),
    path('project/apply/<int:pk>', views.apply_all, name='apply_all'),
    path('project/file-detail/<int:pk>', views.file_detail, name='file_detail'),
    path('project/<int:pk>/<str:file_name>/', views.file_image, name='file_image'),
    path('project/control-data/<int:zip_id>/', views.control_data, name='control_data'),
    
]

aiproject/web/project/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    username = models.CharField(max_length=50, unique=True)
    password = models.TextField()
    email = models.EmailField(unique=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username


class Project(models.Model):
    PROJECT_MODELS = (
        ("YOLO-V8", 'YOLO-V8'),
        ("YOLO-V7", 'YOLO-V7'),
        ("YOLO-V6", 'YOLO-V6'),
        ("YOLO-V5", 'YOLO-V5'),
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    project_image = models.ImageField(upload_to='project-images')
    project_name = models.CharField(max_length=100)
    project_model = models.CharField(max_length=20, choices=PROJECT_MODELS)
    is_public = models.BooleanField(default=True)
    created_time = models.DateTimeField(auto_now_add=True)
    changed_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.project_name


class ColorSpace(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='colorspace')

    def __str__(self):
        return self.name

aiproject/web/project/forms.py
from django import forms
from django.forms import models, Textarea, CharField
from project.models import Project


class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['owner', 'project_image', 'project_name', 'project_model']

aiproject/web/project/views.py
import os

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from project.models import Project, ColorSpace
from upload.models import UploadedZip
from project.forms import CreateProjectForm
from django.http import HttpResponse
from dotenv import load_dotenv
import zipfile
from backend.veri_hazirlama import VeriHazirlama

load_dotenv()  # loading .env file


# if user is not logged in, don't show the page.
# this function returns current user's projects.
# project function
@login_required
def projects(request):
    projects = Project.objects.filter(owner=request.user)
    context = {
        'projects': projects,
    }
    return render(request, 'project/project.html', context)


# when you want to create a new project, this function will be call.
# this function work with forms. Forms get from forms.py.
# if method==post, get values from form and create a new row in our database. Then save.
# if method==get, forms will load. And return a form with htmx library.(search about it)
def create_project(request):
    if request.method == 'POST':
        project_image = request.FILES['project_image']
        project_name = request.POST['project_name']
        project_model = request.POST['project_model']
        if not project_image:
            return HttpResponse('please load a image')
        elif not project_name:
            return HttpResponse('please fill in all the fields')
        elif not project_model:
            return HttpResponse('please fill in all the fields')
        else:
            project = Project.objects.create(owner_id=request.user.id,
                                            project_image=project_image,
                                            project_name=project_name,
                                            project_model=project_model)
            project.save()
            return redirect('/')
    else:
        form = CreateProjectForm()
        context = {
            'form': form,
        }
        return render(request, 'project/partials/create-project.html', context)


# when user click a project this function will work
# if method is post, first get old datas selected project
# then if user wants change the current datas get input datas.
# if user don't want change the old photo, set project_image as old project-image
# then update new datas to database and redirect project detail page again
# if method is get load project informations
def project_detail(request, pk):
    if request.method == 'POST':
        instance = Project.objects.get(id=pk)
        project_name = request.POST['name_input']
        project_model = request.POST['model_choice']
        if request.POST['image-input']:
            project_image = request.POST['image-input']
        else:
            project_image = instance.project_image
        Project.objects.update(project_name=project_name,
                               project_model=project_model,
                               project_image=f'project-images/{project_image}')

        return redirect(f'/project/{pk}')
    else:
        project = Project.objects.get(id=pk)
        try:
            file = UploadedZip.objects.get(project_id=pk)
            context = {
                'project': project,
                'file': file,
            }
        except UploadedZip.DoesNotExist:
            context = {
                'project': project,
            }
        return render(request, 'project/project-detail.html', context)


# when the user want to delete a project, this function will be work.
# first get the selected project
# then get project image path
# create a try except to be sure deleting item.
# use os.remove() for delete item
# after that delete the project from database and redirect home link
def delete_project(request, pk):
    project = Project.objects.get(id=pk)  # get project object
    try:
        project_file = UploadedZip.objects.get(project_id=pk)
        project_image_path = f'C:/Users/ali.yildirim/projects/aiproject/web{project.project_image.url}' # get item path
        project_file_path = f'C:/Users/ali.yildirim/projects/aiproject/web{project_file.zip_file.url}'
        # change this path when you deploy the website !!!!
        os.remove(project_image_path)  # remove item
        os.remove(project_file_path)  # remove file
        print('the image successfully deleted')  # print successful
    except UploadedZip.DoesNotExist:
        project = Project.objects.get(id=pk)  # get project object
        project_image_path = f'C:/Users/ali.yildirim/projects/aiproject/web{project.project_image.url}' # get item path
        os.remove(project_image_path)  # remove item
        print('the image successfully deleted')  # print successful
    except OSError as error:
        print(f'Error deleting file {project_image_path}: {error}')  # print error
        print(f'Error deleting file {project_file_path}: {error}')  # print error

    project.delete()  # delete from database
    return redirect('/')


def file_detail(request, pk):
    zip = UploadedZip.objects.get(id=pk)
    with zipfile.ZipFile(zip.zip_file, 'r') as zip_file:
        list = zip_file.namelist()
        context = {
            'zip': zip,
            'zip_list': list,
            'pk': pk,
        }
    return render(request, 'project/file-detail.html', context)


def file_image(request, pk, file_name):
    zip = UploadedZip.objects.get(id=pk)
    with zipfile.ZipFile(zip.zip_file, 'r') as myzip:
        img_info = myzip.getinfo(file_name).filename
        with myzip.open(img_info) as image:
            img = image.read()
            return HttpResponse(content=img, content_type='image/jpeg')



# when user want to choose color space, this function will work
# get pk in url, and c_space -> write this param in your redirect url
# first get current project
# define try except block for getting choice
# if c_space not null get choice
# else get original image from database
def color_space(request, pk, c_space=None):
    project = Project.objects.get(id=pk)
    try:
        image = ColorSpace.objects.get(name=c_space)
    except ColorSpace.DoesNotExist:
        image = ColorSpace.objects.get(name='original')
    context = {
        'project': project,
        'image': image.image,
        'image_name': image.name,
    }
    return render(request, 'project/colorspace.html', context)


def change_image(request, color_space):
    image = ColorSpace.objects.get(name=color_space).image
    return render(request, 'project/return-image.html', {'image': image})


def apply_all(request, pk):
    return HttpResponse(f"<div class='alert' id='closeBtn'>Colorspace applied for all images successfully"
                        f"<a href='/project/colorspace/{pk}'>"
                        f"<i class='fa-solid fa-xmark'></i>"
                        f"</a>"
                        "</div>")


def control_data(request, zip_id):
    zip_file = UploadedZip.objects.get(id=zip_id).zip_file
    load_dotenv()
    size = (2160, 3840)
    path = f"{os.getenv('FILE')}{zip_file.url}" '/media/project-files/zipname'
    control = VeriHazirlama(path=path, size=size).remove()
    return render(request, 'project/partials/_control-data.html', context={'result': control})


def convert_data(request, zip_id, class_dict):
    pass

aiproject/web/project/templates/project/colorspace.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'project/css/colorspace.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
        <!-- include sidebar-->
        {% include 'project/partials/_sidebar.html' %}

        <!-- color spaces -->
        <div class="col-md-9">
            <div class="box ">
                <div class="row content-center mt-4 mb-4" >
                    <div id="alert" >
                        <!-- success or error alert will be here -->
                    </div>
                </div>
                <div class="row content-center" id="image">
                    <img class="image" src="{{ image.url }}" alt="">
                </div>
                <div class="row content-center">
                    <!-- color space buttons and links -->
                    <div class="grid">
                        <!-- to original -->
                        <button class="button blue" hx-get="{% url 'project:change_image' color_space='original' %}"
                                                    hx-trigger="click" hx-target="#image" hx-swap="innerHTML">
                        </button>
                        <!-- to hsv -->
                        <button class="button green" hx-get="{% url 'project:change_image' color_space='hsv' %}"
                                                     hx-target="#image" hx-swap="innerHTML">

                        </button>
                        <!-- to rgb -->
                        <button class="button red" hx-get="{% url 'project:change_image'  color_space='rgb' %}"
                                                   hx-target="#image" hx-swap="innerHTML">

                        </button>
                        <!-- to gray -->
                        <button class="button gray" hx-get="{% url 'project:change_image' color_space='gray' %}"
                                                    hx-target="#image" hx-swap="innerHTML">

                        </button>
                        <!-- to original link -->
                        <a class="link" hx-get="{% url 'project:change_image' color_space='original' %}"
                                        hx-target="#image"
                                        hx-swap="innerHTML">
                                        ORIGINAL
                        </a>
                        <!-- to hsv link -->
                        <a class="link" hx-get="{% url 'project:change_image' color_space='hsv' %}"
                                        hx-target="#image"
                                        hx-swap="innerHTML">
                                        HSV
                        </a>
                        <!-- to rgb link -->
                        <a class="link" hx-get="{% url 'project:change_image' color_space='rgb' %}"
                                        hx-target="#image"
                                        hx-swap="innerHTML">
                                        RGB
                        </a>
                        <!-- to gray link -->
                        <a class="link" hx-get="{% url 'project:change_image' color_space='gray' %}"
                                        hx-target="#image"
                                        hx-swap="innerHTML">
                                        GRAY
                        </a>
                    </div>
                </div>
                <div class="row content-center mt-5">
                    <a class="applyAllBtn mb-5" hx-get="{% url 'project:apply_all' pk=project.id %}"
                                           hx-target="#alert"
                                           hx-swap="innerHTML"
                                           hx-trigger="click">
                                           Apply Effect All Of Them
                    </a>
                </div>
            </div>

        </div>

    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'project/js/colorspace.js' %}"></script>
{% endblock %}

aiproject/web/project/templates/project/file-detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'project/css/file-detail.css' %}">
    <link rel="stylesheet" href="{% static 'project/css/control-data.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
         <!-- including sidebar -->
        {% include 'project/partials/_sidebar.html' %}


            <!-- file details -->
        <div class="col-md-9">
            <div class="row">
                <a hx-get="{% url 'project:control_data' zip.id %}"
                   hx-trigger="click"
                   class="control-data">Control Data</a>
            </div>
            <table>
                <thead>
                    <tr>
                        <th colspan="2">{{ zip }} zip file</th>
                    </tr>
                </thead>
                <tbody>
                    {% for zip in zip_list  %}
                        <tr>
                            <td class="zip_name">
                                <p>{{ zip }}</p>
                            </td>
{#                            <td class="zip_link">#}
{#                                <a href="{% url 'project:file_image' pk=pk file_name=zip %}">#}
{#                                    <i class="fa-regular fa-image"></i>#}
{#                                </a>#}
{#                            </td>#}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

aiproject/web/project/templates/project/project-detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'project/css/project-detail.css' %}">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <!-- include sidebar -->
            {% include 'project/partials/_sidebar.html' %}

            <!-- project details -->
            <div class="container" style="width: 100%">
                <div class="row">
                    <div class="col-md-7">
                        <div class="card ms-5">

                            <div class="project-header d-flex gap-3 align-items-center">
                                <img class="project-image" src="{{ project.project_image.url }}" alt="">
                                <div class="info">
                                    <p class="project-name">{{ project.project_name }}</p>
                                    <div class="row gap-05 align-items-center">
                                        <i class="fa-regular fa-user"></i>
                                        <p class="project-user">{{ user.username }}</p>
                                    </div>
                                </div>
                            </div>
                            <!-- project body -->
                            <div class="project-body padding-025">
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <label for="name_input">Project Name:</label>
                                    <input type="text" id="name_input" name="name_input"
                                           class="form-control" value="{{ project.project_name }}">

                                    <label for="model_choice">Project Model:</label>
                                    <select name="model_choice" id="model_choice" aria-selected="{{ project.project_model }}">
                                        <option value="YOLO-V8">YOLO-V8</option>
                                        <option value="YOLO-V7">YOLO-V7</option>
                                        <option value="YOLO-V6">YOLO-V6</option>
                                        <option value="YOLO-V5">YOLO-V5</option>
                                    </select>

                                    <label for="image-input">Project Image:</label>
                                    <input type="file" id="image-input" name="image-input" class="form-control">
                                    <div class="row w-93 jc-between">
                                        <!-- save changes -->
                                        <button type="submit" class="saveBtn">
                                            Save Changes
                                            <i class="fa-solid fa-check"></i>
                                        </button>
                                        <!-- delete project  -->
                                        <a href="{% url 'project:delete-project' pk=project.id %}" class="deleteBtn">
                                            Delete Project
                                            <i class="fa-regular fa-trash-can"></i>
                                        </a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="little-card content-center">
                            <p class="add_file">Add your zip file</p>
                            <a href="{% url 'upload:upload_zip' pk=project.id %}">
                                <i class="fa-solid fa-plus"></i>
                            </a>
                        </div>

                        <!-- if file already uploaded, show file-->
                        {% if file %}
                            <div class="uploaded-zip mt-5">
                                <div class="upload-card content-center">
                                    <p class="upload-header">Uploaded File</p>
                                    <i class="fa-solid fa-folder" style="color: #ebc50a;font-size: 64px"></i>
                                    <p class="upload-file-name">{{ file.name }}</p>
                                </div>
                            </div>

                            <div class="row align-items-center buttons">
                                <!-- colorspace choice page -->
                                <div class="colorspace">
                                    <a href="{% url 'project:color-space' pk=project.id %}" class="colorSpaceBtn">
                                        Choice Color Space
                                    </a>
                                </div>

                                <!-- zip file details page -->
                                <div class="file-details">
                                    <a href="{% url 'project:file_detail' pk=file.id %}" class="fileDetailBtn">
                                        Show File Details
                                    </a>
                                </div>
                            </div>

                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

aiproject/web/project/templates/project/project.html
{% extends 'base.html' %}
{% load static %}

<!-- including stylesheets -->
{% block style %}
    <link rel="stylesheet" href="{% static 'project/css/project.css' %}">
    <link rel="stylesheet" href="{% static 'project/css/navbar.css' %}">
{% endblock %}

<!-- including base codes -->
{% block content %}

    <div class="container">
        <div class="row">

            <!-- include sidebar -->
            {% include 'project/partials/_sidebar.html' %}

            <!-- projects -->
            <div class="col-md-10">
                <div class="main-bar">
                    <!-- create new project -->
                    <div class="create-project">
                        <button id="popupBtn" type="button"  hx-get="{% url 'project:create-project' %}" hx-trigger="click" hx-target="#modal"
                         hx-swap="innerHTML">
                            Create New Project
                        </button>
                    </div>
                    <!-- list projects -->
                    <div class="row side-padding wrap gap-1">
                        <!-- project -->
                        {% if projects %}
                            {% for project in projects %}
                            <div class="col-md-4">
                                <div class="card">
                                    <a class="row gap-2 align-items-center"
                                       href={% url 'project:project-detail' pk=project.id  %}>
                                        <img class="project-image" src="{{ project.project_image.url }}" alt="">
                                        <div class="project-info">
                                            <div class="row align-items-center gap-05 ">
                                                <i class="fa-solid fa-globe"></i>
                                                <p class="project-name ">{{ project.project_name }}</p>
                                            </div>
                                            <p class="project-model">{{ project.project_model }}</p>
                                            <p class="project-date">{{ project.created_time }}</p>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                        {% else %}
                            <h1 class="message">henüz gösterilecek bir proje yok!</h1>
                            <img class="no-data" src="{% static 'project/img/no-data.png' %}" alt="">
                        {% endif %} 

                    </div>
                </div>

            </div>
            <!-- end projects -->
        </div>
    </div>

    <div class="backdrop" id="backdrop">
        <div class="modal" id="modal">
            <!-- project create form will be here -->
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'project/js/dialog.js' %}"></script>
{% endblock %}

aiproject/web/project/templates/project/return-image.html
<img class="image" src="{{ image.url }}" alt="">